### ISSUE TITLE
[BUG] CORS headers not added to response

### ISSUE THREAD

**Issue by craquet** [ror-community/ror-roadmap#343]
I am trying to integrate the ROR API into my web application to fetch information on specific ROR identifiers. Unfortunately, the response from the ROR API does not include the necessary CORS headers like `access-control-allow-origin`. Judging by ror-community/ror-api#485 this is not intentional behavior.

To reproduce, simply make a request to this URL and inspect the response headers:

    https://api.ror.org/v2/organizations/04t3en479

Making the request via `fetch()` or by just entering it into the browsers address bar makes no difference in my case.

**Comment by adambuttrick** [comment]
Confirmed user report:

```
set -euo pipefail

URL="${1:-https://api.ror.org/v2/organizations/04t3en479}"
HEADER="access-control-allow-origin"

echo "Requesting: $URL"
echo

HEADERS="$(curl -sSL -D - -o /dev/null "$URL")"

echo "Response headers:"
echo "$HEADERS"
echo

if printf '%s\n' "$HEADERS" | tr '[:upper:]' '[:lower:]' | grep -q "^$HEADER:"; then
  echo "'$HEADER' header is present."
  exit 0
else
  echo "'$HEADER' header is missing."
  exit 1
fi
```
```
Requesting: https://api.ror.org/v2/organizations/04t3en479

Response headers:
HTTP/2 200 
date: Tue, 11 Nov 2025 16:33:50 GMT
content-type: application/json
content-length: 2001
x-amzn-requestid: 80cd2b9a-f310-4e42-b94d-a63d8b124436
allow: GET, PUT, HEAD, OPTIONS
x-amzn-remapped-content-length: 2001
x-frame-options: SAMEORIGIN
x-amzn-remapped-connection: keep-alive
x-amz-apigw-id: T4zJWFVkjoEERaA=
vary: Cookie, Origin
x-amzn-remapped-server: nginx/1.18.0 + Phusion Passenger 6.0.7
status: 200 OK
x-powered-by: Phusion Passenger 6.0.7
x-amzn-remapped-date: Tue, 11 Nov 2025 16:33:50 GMT


'access-control-allow-origin' header is missing.
```

**Comment by adambuttrick** [comment]
Harvard Dataverse is reporting what looks to be the same issue. Calls to the ROR API v2 endpoint for retrieving organizations by ID (/v2/organizations/{id}) are intermittently failing due to missing CORS headers. The Access-Control-Allow-Origin header is sometimes present (set to *) and sometimes absent, causing JavaScript requests from webpages to be blocked by the browser. The search endpoint (organizations?query={query}) appears unaffected.

**Comment by adambuttrick** [comment]
We pushed a patch for this to production. @vera could you test to confirm?

**Comment by craquet** [comment]
I still don't see the CORS headers on my end

**Comment by jrhoads** [comment]
@craquet We just published another patch.  See if this takes care of things.

**Comment by craquet** [comment]
Curiously, I still don't see the header when opening the page above in a new browser tab, but `fetch`ing it works just fine with the correct header included. In any case, that resolves the issue for me. Thank you 😄
